title: 귀찮아도 들이자 기록하는 습관
email: koombayah97@gmail.com
description: "퍼 오는 블로그 말고, 퍼 가는 블로그"
baseurl: "" # 사이트의 하위 경로, 예: /blog
url: "https://Jiggy97.github.io" # 사이트의 기본 호스트 이름 및 프로토콜, 예: http://example.com
github_username: Jiggy97

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

markdown: kramdown
kramdown:
  input: GFM
